name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to deploy'
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            path: ${{ github.event.inputs.artifact-name }}
        - name: List files
          run: ls 
        - name: Output information
          run: echo "Deploying & uploading..."